[tool.poetry]
name = "social-data-ai-agent"
version = "0.1.0"
description = ""
authors = ["Anwesh43 <anweshthecool0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
pydantic-ai = "^2.54.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
